# Generated by Django 5.2.3 on 2025-06-19 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(blank=True, max_length=255, null=True)),
                ('services_offered', models.TextField(blank=True, null=True)),
                ('hours_of_operation', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_conditions', models.TextField(blank=True, null=True)),
                ('contact_preferences', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='business_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_infos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
