# Generated by Django 5.2.3 on 2025-06-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='document',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='business_docs/'),
        ),
    ]
