# Generated by Django 5.2.3 on 2025-06-19 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_alter_businessinfo_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('faq', 'FAQ Document'), ('about', 'About Us'), ('services', 'Services Brochure'), ('pricing', 'Pricing Guide'), ('policies', 'Company Policies'), ('training', 'Training Materials'), ('scripts', 'Call Scripts'), ('other', 'Other')], max_length=20)),
                ('document', models.FileField(max_length=500, upload_to='business_docs/')),
                ('extracted_content', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
