# Generated by Django 5.2.3 on 2025-06-19 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_businessdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessinfo',
            name='document',
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='business_infos', to='llm.businessdocument'),
        ),
        migrations.CreateModel(
            name='AboutUsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_history', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('core_values', models.TextField(blank=True)),
                ('team_info', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('unique_selling_points', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_info', to='llm.businessdocument')),
            ],
        ),
        migrations.CreateModel(
            name='CallScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_type', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_scripts', to='llm.businessdocument')),
            ],
        ),
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_entries', to='llm.businessdocument')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_infos', to='llm.businessdocument')),
            ],
        ),
        migrations.CreateModel(
            name='PricingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_or_package', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('payment_terms', models.TextField(blank=True)),
                ('discounts', models.TextField(blank=True)),
                ('additional_fees', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_infos', to='llm.businessdocument')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_audience', models.CharField(blank=True, max_length=255)),
                ('benefits', models.TextField(blank=True)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_infos', to='llm.businessdocument')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_materials', to='llm.businessdocument')),
            ],
        ),
    ]
